"""Ordinary-member community replies, independent of administrator command text."""
from utils.payout_language import language
KEYS=('updated','counts','channel','role','error','owner','stale')
ROWS={
'English':('Language roles updated.','Total invites: {total}; verified invites: {verified}.','Please use the language channel.','Language role configuration or hierarchy is invalid. Contact an administrator.','Unable to complete this action. Reopen the latest message or contact an administrator.','Only the user who opened this window can use it.','The content has changed. Reopen the latest message and read it again.'),
'中文':('语言身份组已更新。','累计邀请：{total}；有效邀请：{verified}。','请在语言频道操作。','语言身份组配置或层级不正确，请联系管理员。','操作未能完成，请重新打开最新消息或联系管理员。','仅打开此窗口的用户可以操作。','内容已变化，请重新打开最新消息并阅读。'),
'日本語':('言語ロールを更新しました。','累計招待：{total}、認証済み招待：{verified}。','言語チャンネルで操作してください。','言語ロールの設定または階層が正しくありません。管理者に連絡してください。','操作を完了できません。最新のメッセージを開き直すか、管理者に連絡してください。','この画面を開いたユーザーのみ操作できます。','内容が変更されました。最新のメッセージを開き直してお読みください。'),
'한국어':('언어 역할이 업데이트되었습니다.','총 초대: {total}; 인증된 초대: {verified}.','언어 채널에서 사용하세요.','언어 역할 설정 또는 계층이 올바르지 않습니다. 관리자에게 문의하세요.','작업을 완료할 수 없습니다. 최신 메시지를 다시 열거나 관리자에게 문의하세요.','이 창을 연 사용자만 사용할 수 있습니다.','내용이 변경되었습니다. 최신 메시지를 다시 열어 읽어 주세요.'),
'Bahasa Indonesia':('Peran bahasa diperbarui.','Total undangan: {total}; terverifikasi: {verified}.','Gunakan kanal bahasa.','Konfigurasi atau hierarki peran bahasa tidak valid. Hubungi admin.','Tindakan tidak selesai. Buka ulang pesan terbaru atau hubungi admin.','Hanya pengguna yang membuka jendela ini yang dapat menggunakannya.','Konten berubah. Buka ulang pesan terbaru dan baca kembali.'),
'Bahasa Melayu':('Peranan bahasa dikemas kini.','Jumlah jemputan: {total}; disahkan: {verified}.','Gunakan saluran bahasa.','Konfigurasi atau hierarki peranan bahasa tidak sah. Hubungi pentadbir.','Tindakan tidak selesai. Buka semula mesej terkini atau hubungi pentadbir.','Hanya pengguna yang membuka tetingkap ini boleh menggunakannya.','Kandungan berubah. Buka semula mesej terkini dan baca lagi.'),
'Tagalog':('Na-update ang language role.','Kabuuang imbitasyon: {total}; beripikado: {verified}.','Gamitin ang language channel.','Mali ang setting o hierarchy ng language role. Kontakin ang admin.','Hindi natapos ang aksyon. Buksan muli ang pinakabagong mensahe o kontakin ang admin.','Ang nagbukas lamang ng window na ito ang maaaring gumamit nito.','Nagbago ang nilalaman. Buksan at basahin muli ang pinakabagong mensahe.'),
'Português':('Cargos de idioma atualizados.','Convites totais: {total}; verificados: {verified}.','Use o canal de idiomas.','Configuração ou hierarquia do cargo de idioma inválida. Contate um administrador.','Não foi possível concluir. Reabra a mensagem mais recente ou contate um administrador.','Somente quem abriu esta janela pode usá-la.','O conteúdo mudou. Reabra a mensagem mais recente e leia novamente.'),
'Español':('Roles de idioma actualizados.','Invitaciones totales: {total}; verificadas: {verified}.','Usa el canal de idiomas.','La configuración o jerarquía del rol de idioma es incorrecta. Contacta con un administrador.','No se pudo completar. Abre de nuevo el último mensaje o contacta con un administrador.','Solo quien abrió esta ventana puede usarla.','El contenido cambió. Abre el último mensaje y vuelve a leerlo.'),
'ภาษาไทย':('อัปเดตบทบาทภาษาแล้ว','คำเชิญทั้งหมด: {total}; ยืนยันแล้ว: {verified}','โปรดใช้ช่องภาษา','การตั้งค่าหรือลำดับบทบาทภาษาไม่ถูกต้อง โปรดติดต่อผู้ดูแล','ดำเนินการไม่สำเร็จ โปรดเปิดข้อความล่าสุดอีกครั้งหรือติดต่อผู้ดูแล','เฉพาะผู้เปิดหน้าต่างนี้เท่านั้นที่ใช้งานได้','เนื้อหาเปลี่ยนแล้ว โปรดเปิดข้อความล่าสุดและอ่านอีกครั้ง'),
'Tiếng Việt':('Đã cập nhật vai trò ngôn ngữ.','Tổng lời mời: {total}; đã xác minh: {verified}.','Vui lòng dùng kênh ngôn ngữ.','Cấu hình hoặc thứ bậc vai trò ngôn ngữ không hợp lệ. Liên hệ quản trị viên.','Không thể hoàn tất. Mở lại tin nhắn mới nhất hoặc liên hệ quản trị viên.','Chỉ người mở cửa sổ này mới có thể sử dụng.','Nội dung đã thay đổi. Mở tin nhắn mới nhất và đọc lại.')}

def text(lang,key,**values): return ROWS.get(lang,ROWS['English'])[KEYS.index(key)].format(**values)

def for_member(member,key,**values): return text(language(member),key,**values)
