"""User-facing security notices; never performs I/O or changes admission rules."""
from utils.payout_language import language

KEYS=('rate','busy','cooldown','hourly','incoming','capacity','invited','links')
ROWS={
'English':('Too many requests. Please wait and try again.','Too many new trades. Please try again in one minute.','Wait {seconds} seconds between new trades. Cancelling does not reset this limit.','Your hourly trade creation limit has been reached. Please try later.','This member already has too many pending invitations. Wait for them to respond.','Trade channel capacity reached. Please wait; existing trades can continue.','Only the invited participant can accept this trade.','Only members with the LV3 role can post links.'),
'中文':('操作过于频繁，请稍后重试。','当前创建交易较多，请一分钟后重试。','创建交易后请等待 {seconds} 秒再发起，取消订单不会重置等待时间。','本小时创建交易次数已达上限，请稍后再试。','对方尚未处理的交易邀请较多，请等待对方处理。','交易频道已达容量上限，请等待已有频道处理完成。现有交易可继续。','只有被邀请的交易对方可以确认。','需要 LV3 身份组才能发送链接。'),
'日本語':('操作が多すぎます。しばらく待ってから再試行してください。','取引の作成が混み合っています。1 分後に再試行してください。','新しい取引を作成する間隔は {seconds} 秒です。キャンセルしても待ち時間はリセットされません。','1 時間あたりの取引作成上限に達しました。後で再試行してください。','相手に未処理の取引招待が多くあります。相手の対応をお待ちください。','取引チャンネル数が上限に達しました。既存の取引は継続できます。空きができるまでお待ちください。','招待された取引相手のみが承認できます。','リンクの投稿には LV3 ロールが必要です。'),
'한국어':('요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.','거래 생성 요청이 많습니다. 1분 후 다시 시도해 주세요.','새 거래를 만들려면 {seconds}초 간격을 두어야 합니다. 취소해도 대기 시간은 초기화되지 않습니다.','시간당 거래 생성 한도에 도달했습니다. 나중에 다시 시도해 주세요.','상대방에게 처리하지 않은 거래 초대가 많습니다. 상대방이 처리할 때까지 기다려 주세요.','거래 채널 수가 한도에 도달했습니다. 기존 거래는 계속할 수 있습니다. 채널에 여유가 생길 때까지 기다려 주세요.','초대받은 거래 상대방만 거래를 수락할 수 있습니다.','링크를 보내려면 LV3 역할이 필요합니다.'),
'Bahasa Indonesia':('Terlalu banyak permintaan. Tunggu sebentar lalu coba lagi.','Terlalu banyak transaksi baru. Coba lagi dalam satu menit.','Beri jeda {seconds} detik antartransaksi baru. Pembatalan tidak mengatur ulang batas ini.','Batas pembuatan transaksi per jam tercapai. Coba lagi nanti.','Anggota ini memiliki terlalu banyak undangan yang belum ditangani. Tunggu tanggapannya.','Kapasitas kanal transaksi penuh. Harap tunggu; transaksi yang ada tetap dapat dilanjutkan.','Hanya pihak yang diundang yang dapat menerima transaksi ini.','Hanya anggota dengan peran LV3 yang boleh mengirim tautan.'),
'Bahasa Melayu':('Terlalu banyak permintaan. Tunggu sebentar dan cuba lagi.','Terlalu banyak urus niaga baharu. Cuba lagi dalam satu minit.','Tunggu {seconds} saat antara urus niaga baharu. Pembatalan tidak menetapkan semula had ini.','Had penciptaan urus niaga sejam telah dicapai. Cuba lagi kemudian.','Ahli ini mempunyai terlalu banyak jemputan yang belum diproses. Tunggu respons mereka.','Kapasiti saluran urus niaga telah penuh. Sila tunggu; urus niaga sedia ada boleh diteruskan.','Hanya pihak yang dijemput boleh menerima urus niaga ini.','Hanya ahli dengan peranan LV3 boleh menghantar pautan.'),
'Tagalog':('Masyadong maraming kahilingan. Maghintay at subukan muli.','Masyadong maraming bagong trade. Subukan muli pagkalipas ng isang minuto.','Maghintay ng {seconds} segundo sa pagitan ng mga bagong trade. Hindi nire-reset ng pagkansela ang limitasyong ito.','Naabot na ang limitasyon sa paggawa ng trade kada oras. Subukan muli mamaya.','Marami nang hindi pa nasasagot na imbitasyon ang miyembrong ito. Hintayin ang kanyang tugon.','Puno na ang mga trade channel. Maghintay muna; maaaring magpatuloy ang mga kasalukuyang trade.','Ang inimbitahang kalahok lamang ang maaaring tumanggap ng trade na ito.','Mga miyembrong may LV3 role lamang ang maaaring magpadala ng link.'),
'Português':('Muitas solicitações. Aguarde e tente novamente.','Muitas negociações novas. Tente novamente em um minuto.','Aguarde {seconds} segundos entre novas negociações. Cancelar não reinicia esse limite.','O limite de criação de negociações por hora foi atingido. Tente mais tarde.','Este membro tem muitos convites pendentes. Aguarde a resposta dele.','O limite de canais de negociação foi atingido. Aguarde; as negociações existentes podem continuar.','Somente o participante convidado pode aceitar esta negociação.','Somente membros com o cargo LV3 podem publicar links.'),
'Español':('Demasiadas solicitudes. Espera e inténtalo de nuevo.','Demasiadas operaciones nuevas. Inténtalo de nuevo en un minuto.','Espera {seconds} segundos entre nuevas operaciones. Cancelar no reinicia este límite.','Has alcanzado el límite de creación de operaciones por hora. Inténtalo más tarde.','Este miembro tiene demasiadas invitaciones pendientes. Espera su respuesta.','Se alcanzó el límite de canales de operaciones. Espera; las operaciones existentes pueden continuar.','Solo el participante invitado puede aceptar esta operación.','Solo los miembros con el rol LV3 pueden publicar enlaces.'),
'ภาษาไทย':('ส่งคำขอบ่อยเกินไป โปรดรอสักครู่แล้วลองอีกครั้ง','มีการสร้างรายการซื้อขายจำนวนมาก โปรดลองอีกครั้งในหนึ่งนาที','เว้นระยะ {seconds} วินาทีระหว่างการสร้างรายการซื้อขายใหม่ การยกเลิกจะไม่รีเซ็ตเวลารอ','สร้างรายการซื้อขายครบจำนวนสูงสุดต่อชั่วโมงแล้ว โปรดลองใหม่ภายหลัง','สมาชิกนี้มีคำเชิญซื้อขายที่ยังไม่ได้ตอบจำนวนมาก โปรดรอให้ตอบก่อน','ช่องซื้อขายเต็มแล้ว โปรดรอ รายการซื้อขายเดิมยังดำเนินต่อได้','เฉพาะผู้ที่ได้รับเชิญเท่านั้นที่ยอมรับการซื้อขายนี้ได้','ต้องมีบทบาท LV3 จึงจะส่งลิงก์ได้'),
'Tiếng Việt':('Quá nhiều yêu cầu. Vui lòng chờ rồi thử lại.','Có quá nhiều giao dịch mới. Vui lòng thử lại sau một phút.','Chờ {seconds} giây giữa các lần tạo giao dịch. Hủy giao dịch không đặt lại thời gian chờ.','Đã đạt giới hạn tạo giao dịch mỗi giờ. Vui lòng thử lại sau.','Thành viên này có quá nhiều lời mời chưa xử lý. Vui lòng chờ họ phản hồi.','Đã đạt giới hạn kênh giao dịch. Vui lòng chờ; giao dịch hiện có vẫn tiếp tục được.','Chỉ người được mời mới có thể chấp nhận giao dịch này.','Chỉ thành viên có vai trò LV3 mới được gửi liên kết.')
}

def text(member,key,**values):
    return ROWS[language(member)][KEYS.index(key)].format(**values)
